include: ./run-jmeter.yaml
 
stages:
  - test

run-jmeter: 
  stage: test   
  environment:
    name: test
  variables: 
    SERVER_URL: google.com
    SERVER_PORT: 443
    VUCOUNT: 2
    LOOPCOUNT: 1
    THINKTIME: 100
    TEST_FILE: myjmxfile.jmx



